# Generated by Django 4.2.7 on 2023-11-01 08:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2023, 11, 1, 8, 0, 5, 667447, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2023, 11, 1, 8, 0, 13, 721769, tzinfo=datetime.timezone.utc), max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+964 7XXXXXXXXX'.", regex='^(?:\\+964|964)?\\s?7\\d{9}$')], verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=datetime.datetime(2023, 11, 1, 8, 0, 19, 343932, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
