# Generated by Django 4.2.7 on 2023-11-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/barcode', verbose_name='barcode/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/image', verbose_name='Product Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/qrcode', verbose_name='qrcode/'),
        ),
    ]
