# Generated by Django 4.2.7 on 2023-11-01 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_bank_signature_picture'),
        ('product', '0002_alter_product_barcode_alter_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default=[('processing', 'Processing')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.customer')),
                ('product', models.ManyToManyField(to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_qnty', models.IntegerField()),
                ('out_qnty', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('service_name', models.CharField(max_length=100)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.customer')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('additional_information', models.TextField(blank=True, help_text='e.g. My phone has missing headphones', max_length=500, null=True, verbose_name='Additional Information (optional)')),
                ('return_reason', models.CharField(choices=[('item is defective or not working', 'Item is defective or not working'), ('item or accessory is missing in the', 'Item or accessory is missing in the'), ('item has missing freebie', 'Item has missing freebie'), ('item does not match decription or picture', 'Item does not match decription or picture'), ('i did not order this size', 'I did not order this size'), ('i received the wrong item', 'I received the wrong item'), ('item does not fit me', 'Item does not fit me'), ("don't want to item anymore", "Don't want to item anymore"), ('item is damaged/broken/has dent or scratches', 'Item is damaged/broken/has dent or scratches')], max_length=70)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_returned_by_customer', models.BooleanField(default=False)),
                ('is_returned_by_supplier', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoice_number', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('purchase_id', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Purchase Date')),
                ('payment_method', models.CharField(choices=[('cash payment', 'Cash Payment'), ('bank payment', 'Bank Payment'), ('online payment', 'Online Payment')], default='cash payment', max_length=20, verbose_name='Payment Type')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr.supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('expense_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.categoryexpense')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_customer_notified', models.BooleanField(default=False)),
                ('is_supplier_notified', models.BooleanField(default=False)),
                ('damaged_date', models.DateField()),
                ('damaged_reason', models.CharField(choices=[('broken', 'Broken'), ('missing', 'Missing'), ('expiry dates over', 'Expiry Dates over'), ('empty', 'Empty')], max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.supplier')),
            ],
        ),
    ]
