# Generated by Django 4.2.7 on 2023-11-01 23:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_bank_signature_picture'),
        ('product', '0003_categoryexpense_order_stock_service_return_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryexpense',
            options={'verbose_name': 'Category Expense', 'verbose_name_plural': 'Categories Expense'},
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('invoice_number', models.CharField(max_length=10, unique=True)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('hand cash', 'Hand Cash'), ('cash on delivery', 'Cash On Delivery'), ('bKash', 'bKash'), ('উপায় (upay)', 'উপায় (upay)'), ('nagad', 'Nagad'), ('dutch-bangla bank', 'Dutch-Bangla Bank'), ('bank payment', 'Bank Payment')], max_length=50)),
                ('status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], max_length=50)),
                ('is_paid', models.BooleanField(default=False, help_text='Is the sale paid? If yes, the status will be set to paid.', verbose_name='Is Paid')),
                ('discount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
