# Generated by Django 4.2.7 on 2023-11-04 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('analytics', '0001_initial'),
        ('hr', '0006_bank_signature_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesanalytics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='customeranalytics',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.customer'),
        ),
    ]
