# Generated by Django 4.2.7 on 2023-11-01 08:33

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_country',
            field=django_countries.fields.CountryField(default='IQ', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(default='IQ', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+964', max_length=128, region='IQ', verbose_name='Phone Number'),
        ),
    ]
