# Generated by Django 4.2.7 on 2023-11-01 09:47

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_customer_delete_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=django_countries.fields.CountryField(default='IQ', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+964', max_length=128, region=None),
        ),
    ]
