# Generated by Django 4.2.7 on 2023-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_account_bank_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='signature_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/signature_pictures', verbose_name='Signature Picture'),
        ),
    ]
